-- Loads the seed files in order. Each file is idempotent (upserts). Run it with psql from the
-- supabase/ folder after the migrations, or paste the files in this order into the SQL editor.
-- The legacy quotations and the customers are generated by scripts/generate-legacy.ts
-- (npm run generate:legacy); `npm run seed` loads the same data through the API instead.
\i seed/catalog.sql
\i seed/rules.sql
\i seed/customers.sql
\i seed/legacy_quotes.sql
