-- Customers: the four given (spec 5.1) and the eight generated (spec 5.2). Generated by scripts/generate-legacy.ts.
insert into customers (name, segment, country) values
  ('Ebrecht Fabrication', 'fabricator', 'AT'),
  ('Halvorn Steel Supply', 'distributor', 'DE'),
  ('Torvane Structures', 'contractor', 'AT'),
  ('Ostervald Engineering', 'engineering', 'DE'),
  ('Quillon Structures', 'contractor', 'IT'),
  ('Tessmer Fabrication', 'fabricator', 'AT'),
  ('Varnholt Engineering', 'engineering', 'CH'),
  ('Adria Marine Works', 'shipyard', 'IT'),
  ('Kestrel Modular', 'modular building', 'DE'),
  ('Rudmark Industrial', 'industrial plant', 'DE'),
  ('Corvin Steel Buildings', 'contractor', 'IT'),
  ('Baltic Frames', 'fabricator', 'DE')
on conflict (name) do update set segment = excluded.segment, country = excluded.country;
