// Loads src/ai/prompts/<step>.md at build time into src/ai/prompts/generated.ts.
// Netlify functions, Vite and tsx all import the generated module. Spec 4.6.
// Run: npm run build:prompts. A test checks that the generated module is up to date.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export type PromptFile = { step: string; version: number; system: string; user: string }

export function parsePrompt(source: string, file: string): PromptFile {
  const fm = /^---\n([\s\S]*?)\n---\n/.exec(source)
  if (!fm) throw new Error(`${file}: missing the version header`)
  const meta = Object.fromEntries(
    fm[1]!
      .split('\n')
      .map((l) => l.split(':').map((s) => s.trim()))
      .filter((p) => p.length === 2)
      .map(([k, v]) => [k, v]),
  ) as Record<string, string>
  const body = source.slice(fm[0].length)
  const sys = /## System\n([\s\S]*?)\n## User\n/.exec(body)
  const usr = /## User\n([\s\S]*)$/.exec(body)
  if (!sys || !usr) throw new Error(`${file}: needs "## System" and "## User" sections`)
  const step = meta.step
  const version = Number(meta.version)
  if (!step || !Number.isInteger(version)) throw new Error(`${file}: header needs step and version`)
  return { step, version, system: sys[1]!.trim(), user: usr[1]!.trim() }
}

export function renderGenerated(prompts: PromptFile[]): string {
  const entries = prompts
    .map((p) => `  ${p.step}: { version: ${p.version}, system: ${JSON.stringify(p.system)}, user: ${JSON.stringify(p.user)} },`)
    .join('\n')
  return (
    '// Generated by scripts/build-prompts.ts from src/ai/prompts/*.md. Do not edit by hand.\n' +
    '// Run `npm run build:prompts` after a prompt change.\n\n' +
    'export type PromptText = { version: number; system: string; user: string }\n\n' +
    'export const PROMPTS = {\n' +
    entries +
    '\n} as const satisfies Record<string, PromptText>\n'
  )
}

export function loadPrompts(dir: string): PromptFile[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => parsePrompt(readFileSync(resolve(dir, f), 'utf8'), f))
}

const isMain = process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const dir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/ai/prompts')
  const prompts = loadPrompts(dir)
  writeFileSync(resolve(dir, 'generated.ts'), renderGenerated(prompts))
  console.log(`Wrote ${prompts.length} prompt(s): ${prompts.map((p) => `${p.step} v${p.version}`).join(', ')}`)
}
