/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DesignIndexRouteImport } from './routes/design/index'
import { Route as DesignAiRouteImport } from './routes/design/ai'
import { Route as DesignArchitectureRouteImport } from './routes/design/architecture'
import { Route as DesignAssumptionsRouteImport } from './routes/design/assumptions'
import { Route as DesignDataRouteImport } from './routes/design/data'
import { Route as DesignDecompositionRouteImport } from './routes/design/decomposition'
import { Route as DesignModelRouteImport } from './routes/design/model'
import { Route as DesignReleasesRouteImport } from './routes/design/releases'
import { Route as DesignVerificationRouteImport } from './routes/design/verification'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsCheckIdRouteImport } from './routes/ops/$checkId'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as DesignScenariosIdRouteImport } from './routes/design/scenarios.$id'
import { Route as RequestsRequestIdIndexRouteImport } from './routes/requests/$requestId.index'
import { Route as RequestsRequestIdRevisionsNRouteImport } from './routes/requests/$requestId.revisions.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignRoute,
} as any)
const DesignAiRoute = DesignAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DesignRoute,
} as any)
const DesignArchitectureRoute = DesignArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DesignRoute,
} as any)
const DesignAssumptionsRoute = DesignAssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => DesignRoute,
} as any)
const DesignDataRoute = DesignDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DesignRoute,
} as any)
const DesignDecompositionRoute = DesignDecompositionRouteImport.update({
  id: '/decomposition',
  path: '/decomposition',
  getParentRoute: () => DesignRoute,
} as any)
const DesignModelRoute = DesignModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => DesignRoute,
} as any)
const DesignReleasesRoute = DesignReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => DesignRoute,
} as any)
const DesignVerificationRoute = DesignVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DesignRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsCheckIdRoute = OpsCheckIdRouteImport.update({
  id: '/ops/$checkId',
  path: '/ops/$checkId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignScenariosIdRoute = DesignScenariosIdRouteImport.update({
  id: '/scenarios/$id',
  path: '/scenarios/$id',
  getParentRoute: () => DesignRoute,
} as any)
const RequestsRequestIdIndexRoute = RequestsRequestIdIndexRouteImport.update({
  id: '/requests/$requestId/',
  path: '/requests/$requestId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRevisionsNRoute =
  RequestsRequestIdRevisionsNRouteImport.update({
    id: '/requests/$requestId/revisions/$n',
    path: '/requests/$requestId/revisions/$n',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/design/ai': typeof DesignAiRoute
  '/design/architecture': typeof DesignArchitectureRoute
  '/design/assumptions': typeof DesignAssumptionsRoute
  '/design/data': typeof DesignDataRoute
  '/design/decomposition': typeof DesignDecompositionRoute
  '/design/model': typeof DesignModelRoute
  '/design/releases': typeof DesignReleasesRoute
  '/design/verification': typeof DesignVerificationRoute
  '/ops/$checkId': typeof OpsCheckIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/design/': typeof DesignIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/design/scenarios/$id': typeof DesignScenariosIdRoute
  '/requests/$requestId/': typeof RequestsRequestIdIndexRoute
  '/requests/$requestId/revisions/$n': typeof RequestsRequestIdRevisionsNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design/ai': typeof DesignAiRoute
  '/design/architecture': typeof DesignArchitectureRoute
  '/design/assumptions': typeof DesignAssumptionsRoute
  '/design/data': typeof DesignDataRoute
  '/design/decomposition': typeof DesignDecompositionRoute
  '/design/model': typeof DesignModelRoute
  '/design/releases': typeof DesignReleasesRoute
  '/design/verification': typeof DesignVerificationRoute
  '/ops/$checkId': typeof OpsCheckIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/design': typeof DesignIndexRoute
  '/ops': typeof OpsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/design/scenarios/$id': typeof DesignScenariosIdRoute
  '/requests/$requestId': typeof RequestsRequestIdIndexRoute
  '/requests/$requestId/revisions/$n': typeof RequestsRequestIdRevisionsNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/design/ai': typeof DesignAiRoute
  '/design/architecture': typeof DesignArchitectureRoute
  '/design/assumptions': typeof DesignAssumptionsRoute
  '/design/data': typeof DesignDataRoute
  '/design/decomposition': typeof DesignDecompositionRoute
  '/design/model': typeof DesignModelRoute
  '/design/releases': typeof DesignReleasesRoute
  '/design/verification': typeof DesignVerificationRoute
  '/ops/$checkId': typeof OpsCheckIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/design/': typeof DesignIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/design/scenarios/$id': typeof DesignScenariosIdRoute
  '/requests/$requestId/': typeof RequestsRequestIdIndexRoute
  '/requests/$requestId/revisions/$n': typeof RequestsRequestIdRevisionsNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/design/ai'
    | '/design/architecture'
    | '/design/assumptions'
    | '/design/data'
    | '/design/decomposition'
    | '/design/model'
    | '/design/releases'
    | '/design/verification'
    | '/ops/$checkId'
    | '/requests/new'
    | '/design/'
    | '/ops/'
    | '/requests/'
    | '/design/scenarios/$id'
    | '/requests/$requestId/'
    | '/requests/$requestId/revisions/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design/ai'
    | '/design/architecture'
    | '/design/assumptions'
    | '/design/data'
    | '/design/decomposition'
    | '/design/model'
    | '/design/releases'
    | '/design/verification'
    | '/ops/$checkId'
    | '/requests/new'
    | '/design'
    | '/ops'
    | '/requests'
    | '/design/scenarios/$id'
    | '/requests/$requestId'
    | '/requests/$requestId/revisions/$n'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/design/ai'
    | '/design/architecture'
    | '/design/assumptions'
    | '/design/data'
    | '/design/decomposition'
    | '/design/model'
    | '/design/releases'
    | '/design/verification'
    | '/ops/$checkId'
    | '/requests/new'
    | '/design/'
    | '/ops/'
    | '/requests/'
    | '/design/scenarios/$id'
    | '/requests/$requestId/'
    | '/requests/$requestId/revisions/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRouteWithChildren
  OpsCheckIdRoute: typeof OpsCheckIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  OpsIndexRoute: typeof OpsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  RequestsRequestIdIndexRoute: typeof RequestsRequestIdIndexRoute
  RequestsRequestIdRevisionsNRoute: typeof RequestsRequestIdRevisionsNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/ai': {
      id: '/design/ai'
      path: '/ai'
      fullPath: '/design/ai'
      preLoaderRoute: typeof DesignAiRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/architecture': {
      id: '/design/architecture'
      path: '/architecture'
      fullPath: '/design/architecture'
      preLoaderRoute: typeof DesignArchitectureRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/assumptions': {
      id: '/design/assumptions'
      path: '/assumptions'
      fullPath: '/design/assumptions'
      preLoaderRoute: typeof DesignAssumptionsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/data': {
      id: '/design/data'
      path: '/data'
      fullPath: '/design/data'
      preLoaderRoute: typeof DesignDataRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/decomposition': {
      id: '/design/decomposition'
      path: '/decomposition'
      fullPath: '/design/decomposition'
      preLoaderRoute: typeof DesignDecompositionRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/model': {
      id: '/design/model'
      path: '/model'
      fullPath: '/design/model'
      preLoaderRoute: typeof DesignModelRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/releases': {
      id: '/design/releases'
      path: '/releases'
      fullPath: '/design/releases'
      preLoaderRoute: typeof DesignReleasesRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/verification': {
      id: '/design/verification'
      path: '/verification'
      fullPath: '/design/verification'
      preLoaderRoute: typeof DesignVerificationRouteImport
      parentRoute: typeof DesignRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/$checkId': {
      id: '/ops/$checkId'
      path: '/ops/$checkId'
      fullPath: '/ops/$checkId'
      preLoaderRoute: typeof OpsCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/scenarios/$id': {
      id: '/design/scenarios/$id'
      path: '/scenarios/$id'
      fullPath: '/design/scenarios/$id'
      preLoaderRoute: typeof DesignScenariosIdRouteImport
      parentRoute: typeof DesignRoute
    }
    '/requests/$requestId/': {
      id: '/requests/$requestId/'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId/'
      preLoaderRoute: typeof RequestsRequestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/revisions/$n': {
      id: '/requests/$requestId/revisions/$n'
      path: '/requests/$requestId/revisions/$n'
      fullPath: '/requests/$requestId/revisions/$n'
      preLoaderRoute: typeof RequestsRequestIdRevisionsNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignRouteChildren {
  DesignAiRoute: typeof DesignAiRoute
  DesignArchitectureRoute: typeof DesignArchitectureRoute
  DesignAssumptionsRoute: typeof DesignAssumptionsRoute
  DesignDataRoute: typeof DesignDataRoute
  DesignDecompositionRoute: typeof DesignDecompositionRoute
  DesignModelRoute: typeof DesignModelRoute
  DesignReleasesRoute: typeof DesignReleasesRoute
  DesignVerificationRoute: typeof DesignVerificationRoute
  DesignIndexRoute: typeof DesignIndexRoute
  DesignScenariosIdRoute: typeof DesignScenariosIdRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignAiRoute: DesignAiRoute,
  DesignArchitectureRoute: DesignArchitectureRoute,
  DesignAssumptionsRoute: DesignAssumptionsRoute,
  DesignDataRoute: DesignDataRoute,
  DesignDecompositionRoute: DesignDecompositionRoute,
  DesignModelRoute: DesignModelRoute,
  DesignReleasesRoute: DesignReleasesRoute,
  DesignVerificationRoute: DesignVerificationRoute,
  DesignIndexRoute: DesignIndexRoute,
  DesignScenariosIdRoute: DesignScenariosIdRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRouteWithChildren,
  OpsCheckIdRoute: OpsCheckIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  OpsIndexRoute: OpsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  RequestsRequestIdIndexRoute: RequestsRequestIdIndexRoute,
  RequestsRequestIdRevisionsNRoute: RequestsRequestIdRevisionsNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
